name: Go CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth-service, user-profile-service, transaction-ledger, risk-detection]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: cd ${{ matrix.service }} && go mod tidy

      - name: Run tests
        run: cd ${{ matrix.service }} && go test ./...

      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          cd ${{ matrix.service }} && golangci-lint run ./...

      - name: Build Docker image
        run: docker build -t ${{ matrix.service }}:latest ./${{ matrix.service }}
