name: Docker CI/CD

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - auth-service
          - user-profile-service
          - transaction-ledger
          - risk-detection

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          echo "🔨 Building image for ${{ matrix.service }}..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Push Docker image
        run: |
          echo "🚀 Pushing image for ${{ matrix.service }} to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

      - name: ✅ Verify Docker push
        run: docker info | grep Username || echo "❌ Not logged in"
